### ISSUE TITLE
Best Practices for Resolvers

### ISSUE THREAD

**Issue by mohamedmansour** [Microsoft/satcheljs#103]
Components like `Picker` which require a "Resolver" that returns a Promise. What is the best practice for that? 

If we call the API directly there, that goes against the Satchel/State Management reason. Because there are side-effect within the View.

For example, we are implementing a ListPicker where when you type a popup appears like an auto suggest. One prop has:

      <ListPicker
          onResolveSuggestions: (filter, selectedItems): Promise<ISuggestions[]> => {
             // BEST Practice getting data from API ? If we call an action, orchestrator cannot communicate
             // here unless the state has a promise type? But that becomes messy?
           
              return somePromise;
         },
      />

**Comment by kenotron** [comment]
Attn: @smikula 

Ahh, after looking at what you're saying here, is there something fundamentally wrong to just have that resolver return a fetched resource? I don't even think satcheljs is involved here...

**Comment by mohamedmansour** [comment]
After talking with kenotron on chat, it seems that if the ListPicker functionality requires a Promise for its state, then fundamentally there is nothing wrong calling a "API Service" side-effect in the View. That is what we are doing, I just thought we could introduce another action "similar to `actionOrchestrator` called `actionOrchestratorPromise` that returns a promise.

**Comment by smikula** [comment]
@mohamedmansour, it sounds like you own the implementation of `ListPicker`, right?  I'm not sure what you talked about with @kenotron, but if `ListPicker` is your component then I'd suggest implementing it in a more cannonical Satchel/MobX pattern.  I.e. the component is just presentation and event handling; to communicate with the rest of the app it dispatches actions.  It should not need to receive a Promise for when the API completes; rather, when the API completes your data layer should update the store, and the component will naturally react to the store change.

(This whole thing gets turned on its head if `ListPicker` is a third-party component that you want to consume, of course, but that doesn't sound like the case.)

**Comment by kenotron** [comment]
In fact `ListPicker` is a "third-party component" - that happens to live in Fabric I think. And as you know Fabric is not mobx / satcheljs aware, so that's what I recommended.

**Comment by kenotron** [comment]
oops, wrong button :)

**Comment by mohamedmansour** [comment]
@smikula  I am using Microsoft Fabric `BasePicker` which requires the response to be a Promise. I will do what kenotron recommended is just do this hack for just resolvers for third party components.
