### ISSUE TITLE
React Hooks

### ISSUE THREAD

**Issue by mohamedmansour** [Microsoft/satcheljs#107]
Hello! I am starting a new project and I am a fan of Satchel Flux architecture, any ideas how we invision Satchel to work with Hooks?

We could create a `satchel-lite` forked repository so that it interfaces well with `mobx-react-lite` 

I was thinking of something along these lines:

```

const onIncrement = mutatorAction('onIncrement', () =>{
   const store = useRootStore()
   store.count++
})

function useRootStore() {
   const store = useStore('RootStore', {
      count: 0
   })
   return store
}

const App = observer(() {
   const state = useRootStore()
   return <button onClick={() => onIncrement()}>Clicked {state.count}</div>
})
```

Right now Satchel doesn't work with React Hooks.  @kenotron  @smikula

**Comment by smikula** [comment]
Can you be more specific about what doesn't work?  Satchel does not interact directly with either `react` or `mobx-react`.  It is just a thin layer on top of MobX itself, so it should work just fine anywhere that MobX works.  (Though I haven't tried Satchel + hooks yet, so it's possible I'm misunderstanding something.)

**Comment by mohamedmansour** [comment]
mobx-react doesn't work with React Hooks, that is why the lead of mobx created mobx-react-lite. When wrapping it with mobx-react observer, it says you cannot run hooks in that method, hence the mobx-react-lite repo

The recommended way for react-hooks for side-effects is to do it in the "useEffect". Right now I am creating an "action" as a hook, for example: `useUserList`, which does all the side effects, and it can be reused in other areas, it seems React Hooks is flux friendly,  "hooks" could act like actions, and each hook has state. So maybe I will try this approach to see if I really need Satchel. Because with hooks, the data is unidirectional.

**Comment by smikula** [comment]
As far as I can tell, hooks work just fine as long as you're using `mobx-react-lite`.  It is possible to use `mobx-react` and `mobx-react-lite` side by side, so you can incrementally port a codebase if necessary. 
 I've coded a working example in the satcheljs-cookbook repo ([link](https://github.com/Microsoft/satcheljs-cookbook/commit/e82066833be2878e051dc95d26299c7691048fc0)).

Even in my example above, I had to come up with something really contrived to even test this.  As a best practice you should not have an observer component that also has state (so no `useState` hook) and in Satchel the recommended way to deal with side effects is by dispatching an action and letting an orchestrator take care of it.  (That's not to say there's anything wrong with hooks, but if you buy into the Satchel pattern you probably shouldn't need them very often.)

@mohamedmansour, let me know if I'm missing something, and if you have problems with `satcheljs` and `mobx-react-lite` please point me to a repro and maybe I can address it.  For now I'll close this issue.
