### ISSUE TITLE
when is the next release planned to move Satchel JS 4.x version out of beta?

### ISSUE THREAD

**Issue by maheshp9** [Microsoft/satcheljs#118]
We are looking forward to upgrade our MobX and Satchel dependencies. Wondering when is Satchel 4.x version going out of beta? Are there any pending issues that is blocking it to release out of beta?

**Comment by smikula** [comment]
No blocking issues—in fact, getting v4 officially out is something that's been on my backlog for ages.  I just release a new beta version (beta3) which includes the last of the changes for v4.  I'd like to validate it in my app for a few weeks before I release it officially, but the official v4 will be functionally identical (barring some bugfixes).

**Comment by mohamedmansour** [comment]
@smikula  let me know how we can help! Bing Ads is using Satchel v3 on two web apps! We are testing it too
