### ISSUE TITLE
Any plan to bump mobx and mobx-react to the latest version?

### ISSUE THREAD

**Issue by haven2world** [microsoft/satcheljs#146]
Since mobx-react supports hook in v6, we cannot use satcheljs with FC and hook together now.

mobx-react:
![image](https://user-images.githubusercontent.com/17299418/104427587-5f8aa100-55be-11eb-85ef-31ab2090b1b7.png)

**Comment by aaaronic** [comment]
My team is seeing the same issue with npm v7.x.

**Comment by smikula** [comment]
This is on our radar; I just need a bit of time to work through the implications of the upgrade.  Should be coming in the next couple months.

**Comment by haven2world** [comment]
Any updates?

**Comment by smikula** [comment]
My product is currently using Satchel with the latest mobx packages with no problems.  I understand the peer dependencies in `package.json` are out of date, but have you tried using Satchel as is?  Assuming it's working fine for you, too, I can get the peer deps updated.

**Comment by haven2world** [comment]
Sure. I just override Satchel's dependencies. Seems to be better to update it in pacakage.json officially

**Comment by smikula** [comment]
I just fixed this with #172 and released a patch version ([v4.3.1](https://github.com/microsoft/satcheljs/releases/tag/v4.3.1)).
