### ISSUE TITLE
Docs: make all code samples to have a consistent style (tslint them somehow?)

### ISSUE THREAD

**Issue by kenotron** [Microsoft/satcheljs#27]

**Comment by JoshuaKGoldberg** [comment]
This would be an interesting utility - something that takes a Markdown file, extracts everything between <code>```ts</code> or <code>```typescript</code> and <code>```</code>, and lints them...

**Comment by ericrallen** [comment]
There's something like this:  https://github.com/eslint/eslint-plugin-markdown

Haven't seen one that works with TSLint, though.

**Comment by smikula** [comment]
I don't think this is a priority at this time.  If someone develops a utility like this that works with TSLint then we can reevaluate.
