### ISSUE TITLE
Docs: add a tutorial section in gitbook, maybe add a package that is a todomvc

### ISSUE THREAD

**Issue by kenotron** [Microsoft/satcheljs#30]

**Comment by smikula** [comment]
This is reasonably covered by [satcheljs-cookbook](https://github.com/Microsoft/satcheljs-cookbook) and [satcheljs-todomvc](https://github.com/Microsoft/satcheljs-todomvc).  Admittedly, both of those repos are due for a refresh with the most current Satchel APIs and patterns, but we should track that in the respective repos.
