### ISSUE TITLE
mobx/mobx-react does not update the render after store data change

### ISSUE THREAD

**Issue by timtong1982** [Microsoft/satcheljs#31]
"dependencies": {
        "@types/react": "^15.0.4",
        "@types/react-dom": "^0.14.21",
#         "mobx": "^3.0.2",
#        "mobx-react": "^4.1.0",
        "react": "^15.4.2",
        "react-dom": "^15.4.2",
#       "satcheljs": "^2.9.0"
    },

**Comment by kenotron** [comment]
I think the issue lies in something being different versions of mobx. I think SatchelJS incorrectly took on mobx as a dependency rather than a peer.

**Comment by smikula** [comment]
I changed `mobx` to be a peer dependency in #86.  Let us know if you run into further issues.
