### ISSUE TITLE
Switch to new version of mobx

### ISSUE THREAD

**Issue by KatSick** [Microsoft/satcheljs#87]
Now with release 3.1.0 we can install latest mobx, however some warnings occurred like

```
[mobx] Deprecated: `mobx.map` is deprecated, use `new ObservableMap` or 
`mobx.observable.map` instead
```

I will try my best to create MR for this

**Comment by mohamedmansour** [comment]
Are you still working on this? There is a warning that satcheljs has incorrect peer dependency 
"mobx@^4.4.0"

**Comment by mohamedmansour** [comment]
@smikula  @kenotron  any plans to update to mobx 5? Stay upto date with latest libraries

**Comment by smikula** [comment]
Exactly this.  My understanding is that MobX v4 is API compatible with v5, so it should be possible to swap in the newer version if you know your browsers support it.  (Or even build different bundles for different browsers with the appropriate version, if you're ambitious.)  But we haven't specifically tested against v5, so I can't promise everything will work.  (Feel free to try it and open issues if you find any!)

**Comment by maheshp9** [comment]
Is there a plan to to release satcheljs 4.x release (out of beta/pre-release) ?
