### ISSUE TITLE
Question: How can i wait promise from action()?

### ISSUE THREAD

**Issue by KatSick** [Microsoft/satcheljs#90]
How can i achieve this behaviour? (check `onClick` method). Maybe i can achive this with middleware somehow ?

```
import * as React from "react";
import { action, orchestrator } from "satcheljs";

import { render } from 'react-dom';

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const someAction = action("some", () => ({}));

orchestrator(someAction, async () => {
  await sleep(2000);
});

class App extends React.Component {
  state = { loading: false };

  onClick = async () => {
    this.setState({ loading: true });
    await someAction();
    this.setState({ loading: false });
  };
  render() {
    return <button onClick={this.onClick}>{this.state.loading.toString()}</button>;
  }
}

render(<App />, document.getElementById('root'));
```

Live demo: https://codesandbox.io/s/jl5k1y0033

**Comment by smikula** [comment]
The short answer is that you cannot await the dispatch of an action.  There are several things in your example that are not idiomatic Satchel usage.  The main purpose of Satchel (or any dataflow library) is to separate application state and the manipulation of it from the UI.  Typically the UI should just dispatch an action without any care for who is listening for it or what the affect of it will be.  If there's some async behavior, that should be encapsulated in an orchestrator.  (And state manipulation should be encapsulated in a mutator.)

Instead of storing state in the component, you'd store it in a store:

```typescript
const getStore = createStore('sampleStore', { loading: false });
```

And you'd render based on the value in the store.  (Don't forget to decorate your component with `@observer` so that MobX knows to update when the store changes!)

```typescript
render() {
    return <button onClick={this.onClick}>{getStore().loading.toString()}</button>;
}
```

For your example case you would actually need two actions:

```typescript
const buttonClicked = action("buttonClicked", () => ({}));
const setLoadingState = action("setLoadingState", (value) => ({ value }));
```

Your onClick handler should be very simple:

```typescript
onClick = () => {
    buttonClicked();
};
```

And the async logic goes into the orchestrator:

```typescript
orchestrator(buttonClicked, async () => {
    setLoadingState(true);
    await sleep(2000);
    setLoadingState(false);
});
```

Finally, you'd have a mutator that listens to `setLoadingState` and modifies the store:

```typescript
mutator(setLoadingState, (actionMessage) => {
    getStore().loading = actionMessage.value;
});
```

**Comment by KatSick** [comment]
First of all, thanks for such detailed answer, and sorry for writing the answer in a closed issue. 

My main goal is not to force you or any other contributor to implement the functionality I mentioned above. Just want to discuss an improvement that I can contribute if it is okay with library's idiomatic way of managing the state. 

The reason why I'm asking about this is the case when I just want to wait for all action chain to finish. So action return data will always be void or Promise<void>. 

The case that I found this super useful is using SatchelJS with Formik and render props:

```
import * as React from 'react'
import { render } from 'react-dom';
import { Formik } from 'formik';
import { createStore, action, orchestrator, mutator } from 'satcheljs';

const store = createStore('root', { token: '' });

const authStart = action('AUTH_START', () => ({}));
const authSuccess = action('AUTH_SUCCESS', (token) => ({ token }));

mutator(authSuccess, ({ token }) => {
  store.token = token
});

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

orchestrator(authStart, async() => {
  await sleep(2000);
  authSuccess('my-secret-token');
});


const App = () =>
  <div>
    <Formik
      initialValues={{
        email: '',
        password: ''
      }}
      onSubmit={async (values, { setSubmitting }) => {
        setSubmitting(true);
        await authStart();
        setSubmitting(false);
      }}
      render={({ values, errors, touched, handleChange, handleBlur, handleSubmit, isSubmitting }) =>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            name="email"
            onChange={handleChange}
            onBlur={handleBlur}
            value={values.email}
          />
          {touched.email && errors.email && <div>{errors.email}</div>}
          <input
            type="password"
            name="password"
            onChange={handleChange}
            onBlur={handleBlur}
            value={values.password}
          />
          {touched.password && errors.password && <div>{errors.password}</div>}
          <button type="submit" disabled={isSubmitting}>Submit</button>
        </form>}
    />
  </div>

render(<App />, document.getElementById('root'))
```

Live demo: https://codesandbox.io/s/2z706897wy

A great example of the similar implementation Vuex state management library, where you can just wait for action but not for the return value, which is useful for some UI stuff.
