### ISSUE TITLE
Deprecate orchestratorAction

### ISSUE THREAD

**Issue by smikula** [Microsoft/satcheljs#91]
The `orchestratorAction` API was intended to be a convenience function to make it easier to implement simple orchestrators, but after seeing it in use for a while it's apparent that it causes more harm than good.  For all the reasons below, we've decided to deprecate it and no longer recommend using it.

1. The signature of an `orchestratorAction` *looks* like it returns a `Promise`, which leads people to think they can await it—but it can't be awaited.  The problem here is a limitation of TypeScript; when decorating a function as an `orchestratorAction` the returned function has to have the same signature as the function passed in.  We want it to have the same *parameters*, but the *return type* should actually be `void`.  This can lead to all sorts of subtle bugs.
2. Because an `orchestratorAction` blurs the line between "orchestrator" and "action", people have a tendency to lump them in with all the other actions.  One goal of v3 is to promote a clear distinction between the data layer (which contains stores and their associated mutators) and the orchestration layer.
3. The other goal of v3 is to promote the Flux mental model of dispatching and handling actions rather than just calling imperative functions.  When you call a function imperatively you have certain expectations—like being able to return a value or await an async function.  By forcing the use of the full action-creator-dispatch-listener pattern it's clear why these things don't make sense.
4. Moreover, using the normal orchestrator pattern is more flexible for when requirements inevitably change.  While it's not that hard to convert an `orchestratorAction` to the full orchestrator pattern, when the "simple" imperative pattern is already in place the inclination is retrofit new requirements into it, at the expense of veering the design farther and farther from Flux.

**Comment by kenotron** [comment]
I find that in the same vein, we should deprecate mutatorAction as well to promote a consistent API across all of SatchelJS.

**Comment by MLoughry** [comment]
I can understand the reasoning for removing `orchestratorAction`, but I think `mutatorAction` is a benign and helpful shortcut.

**Comment by mohamedmansour** [comment]
Are we going to do this? :)
